#!/usr/bin/env sh

unset ZENIN_DB_KIND
unset ZENIN_DB_ADDRESS
unset ZENIN_DB_PORT
unset ZENIN_DB_NAME
unset ZENIN_DB_USERNAME
unset ZENIN_DB_PASSWORD
unset ZENIN_TLS_CERT
unset ZENIN_TLS_KEY
unset ZENIN_RT_LEVEL
unset ZENIN_RT_REDIRECT
unset ZENIN_RT_PORT

unset ZENIN_CONTAINER
unset ZENIN_DB_CONTAINER

unset ZENIN_API_USER
unset ZENIN_API_PASS
unset ZENIN_API_TOKEN
