/*!
 * A simple infrastructure monitoring tool.
 *
 * This program ingests data streams generated by probes and external systems
 * into structured forms that can assist with SLA reporting and alerting.
 *
 * It is designed to scale gracefully with the user and operate with a minimal
 * footprint. In a simple configuration, it can collect and process information
 * over short durations with no dependency on external storage. Likewise, more
 * advanced configurations may exist for more advanced use cases.
 *
 * The next sections describe some core concepts in isolation.
 *
 * # Station
 *
 * Stations are individual installations of the program that exist on one or
 * more computers in a network. They are like hoppers that process incoming
 * data, and may be equipped with probes that can generate data.
 *
 * ```text
 *
 *              ┌─────────────────── STREAM 1
 *              │ ┌─────────────s─── STREAM 2
 *       SAMPLE s │
 *              │ │
 *              ▼ ▼
 *         │           │
 *         │           │
 *         │           │
 *         │         ◄─┼─s─ PROBE
 * STATION └─────┬─────┘
 *               s
 *               │
 *               ▼
 *
 * ```
 *
 * # Metric
 *
 * Metrics are the smallest units of information processed by a Station.
 * They are defined by a unique identity, which is a metric name combined with
 * zero or more key/value labels, and a value.
 *
 * ```text
 *
 *          METRIC A
 *          ┌────────────────────────┐
 * IDENTITY │ disk.used{subject="A"} │
 * VALUE    │ 30.0                   │
 *          └────────────────────────┘
 *
 *           METRIC B
 *          ┌────────────────────────┐
 *          │ disk.used{subject="B"} │
 *          │ 97.0                   │
 *          └────────────────────────┘
 *
 * ```
 *
 * # Sample
 *
 * Samples contain one timestamp, and one or more metrics.
 *
 * ```text
 *
 *           SAMPLE A
 *           ┌───────────────────────┐
 * IDENTITY  │ cpu.user{subject="A"} │
 * VALUE     │ 42.6                  │
 * IDENTITY  │ cpu.sys{subject="A"}  │
 * VALUE     │ 12.0                  │
 * IDENTITY  │ cpu.idle{subject="A"} │
 * VALUE     │ 45.4                  │
 * TIMESTAMP │ 1767250800            │
 *           └───────────────────────┘
 *
 * ```
 *
 * # Monitor
 *
 * Monitors are rules that allow the system to react to metrics.
 *
 * They contain a condition and an action. When a metric is received by a
 * station and matches the condition of a monitor, the action is executed.
 *
 * ```text
 *
 *                  METRIC
 *           ┌──────▼──────────┐
 * CONDITION │ disk.used >= 90 │
 * ACTION    │ send_alert      │
 *           └──────▼──────────┘
 *                  ACTION ──► send_alert()
 *
 * ```
 *
 * # Probe
 *
 * Probes are components that can generate metrics.
 * Depending on probe capabilities, it may be possible to retrieve information
 * about the local system, or poll a remote device across a network.
 *
 * For remote environments, a minimal station can be deployed directly to the
 * device to act as a transmitter by pushing samples upstream.
 *
 * ```text
 *
 * REMOTE DEVICE
 * ┌──────────────────────────────────────────┐
 * │ ┌──────┐   ┌─────────────┐   ┌─────────┐ │
 * │ │ DISK │──►│ SMART PROBE │──►│ STATION │ │
 * │ └──────┘   └─────────────┘   └────┬────┘ │
 * └───────────────────────────────────┼──────┘
 *                                     │
 *                                     │ NETWORK
 * LOCAL DEVICE                        │
 * ┌───────────────────────────────────│──────┐
 * │ ┌──────┐   ┌─────────────┐   ┌────▼────┐ │
 * │ │ DISK │──►│ SMART PROBE │──►│ STATION │ │
 * │ └──────┘   └─────────────┘   └────▲────┘ │
 * │            ┌─────────────┐────────┘      │        ┌───────────────┐
 * │            │ HTTP PROBE  │◄──────────────┼────────┤ REMOTE SERVER │
 * │            └─────────────┘               │        └───────────────┘
 * └──────────────────────────────────────────┘
 *
 * ```
 */

#![allow(dead_code)]

use zenin::engine::Engine;
use zenin::probe::cpu;

fn leak<T>(value: T) -> &'static mut T {
    Box::leak(Box::new(value))
}

// fn intern_strings(dict: &mut StringPool) -> StringHandles {
//     StringHandles {
//         probe: process::ProbeHandles::register(dict),
//     }
// }
//
// struct StringHandles {
//     probe: process::ProbeHandles,
// }

////////////////////////////////////////////////////////////////////////////////

const DEFAULT_RING_SIZE: usize = 3600;


fn main() {
    let mut engine = Engine::new(DEFAULT_RING_SIZE);

    println!("registering cpu probe...");
    cpu::CMedicCpuProbe::register(&mut engine);

















    // let proc = process::ProcessProbe {
    //     command: "/usr/bin/curl",
    //     args: &["-s", "https://example.com"],
    //     timeout_ms: 10,
    //     stdout_max: 2048,
    //     stderr_max: 2048,
    // };
    //
    // let now = now();
    // let timer = Instant::now();
    //
    // proc.sample(|name, value| {
    //     println!("{}: {}: {}", now, name, value);
    // });
    //
    // let elapsed_ms = timer.elapsed().as_secs_f64() * 1000.0;
    // let duration_ms_id = MetricId::new(strings.id_or_insert("probe.duration_ms"), &[]);
    // let timeout_ms_f64 = proc.timeout_ms as f64;
    // let duration_ms = if elapsed_ms >= timeout_ms_f64 {
    //     timeout_ms_f64
    // } else {
    //     elapsed_ms
    // };
    //
    // println!(
    //     "{}: {}: {}",
    //     now,
    //     strings.str(duration_ms_id.name).unwrap(),
    //     duration_ms
    // );
}
