/*!
 * A simple infrastructure monitoring tool.
 *
 * This program ingests data streams generated by probes and external systems
 * into structured forms that can assist with SLA reporting and alerting.
 *
 * It is designed to scale with the user and operate with a minimal footprint.
 * In a simple configuration, it can collect and process information over short
 * durations with no dependency on external storage.
 * Likewise, more advanced configurations may exist for more advanced use cases.
 *
 * # Station
 *
 * Stations are individual installations of the program. They are like hoppers
 * that process incoming data, and may be equipped with probes that can generate
 * data.
 *
 * ```text
 *
 *              ┌─────────────────── STREAM 1
 *              │ ┌─────────────x─── STREAM 2
 *         DATA x │
 *              │ │
 *              ▼ ▼
 *         │           │
 *         │           │
 *         │           │
 *         │         ◄─┼─x─ PROBE
 * STATION └─────┬─────┘
 *               x
 *               │
 *               ▼
 *
 * ```
 *
 * # Metric
 *
 * Metrics describe a stream of data stored in the engine.
 * They contain a name, zero or more key-value labels, and a value.
 *
 * ```text
 *
 *          ┌────────────────────┐
 * IDENTITY │ disk.used{sub="A"} │
 *          └────────────────────┘
 *          ┌────────────────────┐
 *          │ disk.used{sub="B"} │
 *          └────────────────────┘
 *
 * ```
 *
 * # Monitor
 *
 * Monitors are rules that react to changes in metric data.
 * They contain a condition and an action.
 *
 * ```text
 *
 *                  METRIC
 *           ┌──────▼──────────┐
 * CONDITION │ disk.used >= 90 │
 * ACTION    │ send_alert      │
 *           └──────▼──────────┘
 *                  ACTION ──► send_alert()
 *
 * ```
 *
 * # Probe
 *
 * Probes generate points of data for a metric series.
 * Depending on probe capabilities, it may be possible to retrieve information
 * about the local system, or poll a remote device across a network.
 *
 * For remote environments, a minimal station can be deployed directly to the
 * device to act as a transmitter by pushing data to another station.
 *
 * ```text
 *
 * REMOTE DEVICE
 * ┌──────────────────────────────────────────┐
 * │ ┌──────┐   ┌─────────────┐   ┌─────────┐ │
 * │ │ DISK │──►│ SMART PROBE │──►│ STATION │ │
 * │ └──────┘   └─────────────┘   └────┬────┘ │
 * └───────────────────────────────────┼──────┘
 *                                     │
 *                                     │ NETWORK
 * LOCAL DEVICE                        │
 * ┌───────────────────────────────────│──────┐
 * │ ┌──────┐   ┌─────────────┐   ┌────▼────┐ │
 * │ │ DISK │──►│ SMART PROBE │──►│ STATION │ │
 * │ └──────┘   └─────────────┘   └────▲────┘ │
 * │            ┌─────────────┐────────┘      │        ┌───────────────┐
 * │            │ HTTP PROBE  │◄──────────────┼────────┤ REMOTE SERVER │
 * │            └─────────────┘               │        └───────────────┘
 * └──────────────────────────────────────────┘
 *
 * ```
 */

#![allow(dead_code, warnings)]

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use zenin::engine::Engine;
use zenin::probe;
use zenin::thread::spawn_interval_loop;

const DEFAULT_RING_SIZE: usize = 4096;

static SHUTDOWN: AtomicBool = AtomicBool::new(false);

fn leak<T>(value: T) -> &'static mut T {
    Box::leak(Box::new(value))
}

fn main() {
    let mut engine = Engine::new(DEFAULT_RING_SIZE);
    let mut cpu_p = probe::cpu::MedicCpuProbe::new(&mut engine);

    let engine = Arc::new(Mutex::new(engine));
    spawn_interval_loop(&SHUTDOWN, engine.clone(), cpu_p);
    // spawn_server(&SHUTDOWN, engine.clone(), "127.0.0.1:23111");

    _ = wait_for_signals(&[SIGINT, SIGTERM]);
    SHUTDOWN.store(true, Ordering::Relaxed);
}

////////////////////////////////////////////////////////////////////////////////
// FFI
////////////////////////////////////////////////////////////////////////////////

use std::ffi::c_int;
use std::mem::MaybeUninit;

pub const SIGBLOCK: c_int = 0;
pub const SIGINT: c_int = 2;
pub const SIGTERM: c_int = 15;

#[repr(C)]
#[allow(non_camel_case_types)]
pub struct sigset_t {
    #[cfg(target_pointer_width = "32")]
    __val: [u32; 32],
    #[cfg(target_pointer_width = "64")]
    __val: [u64; 16],
}

unsafe extern "C" {
    fn sigemptyset(set: *mut sigset_t) -> c_int;
    fn sigaddset(set: *mut sigset_t, signum: c_int) -> c_int;
    fn pthread_sigmask(how: c_int, set: *const sigset_t, oldset: *mut sigset_t) -> c_int;
    fn sigwait(set: *const sigset_t, sig: *mut c_int) -> c_int;
}

pub fn wait_for_signals(signals: &[c_int]) -> c_int {
    unsafe {
        let mut set = MaybeUninit::<sigset_t>::uninit();
        sigemptyset(set.as_mut_ptr());
        for &sig in signals {
            sigaddset(set.as_mut_ptr(), sig);
        }

        pthread_sigmask(SIGBLOCK, set.as_ptr(), std::ptr::null_mut());

        let mut caught_sig: c_int = 0;
        sigwait(set.as_ptr(), &mut caught_sig);

        return caught_sig;
    }
}
