/*!
 * A simple infrastructure monitoring tool.
 *
 * This program ingests data streams generated by probes and external systems
 * into structured forms that can assist with SLA reporting and alerting.
 *
 * It is designed to scale with the user and operate with a minimal footprint.
 * In a simple configuration, it can collect and process information over short
 * durations with no dependency on external storage.
 * Likewise, more advanced configurations may exist for more advanced use cases.
 *
 * The next sections describe some core concepts in isolation.
 *
 * # Station
 *
 * Stations are individual installations of the program that exist on one or
 * more computers in a network. They are like hoppers that process incoming
 * data, and may be equipped with probes that can generate data.
 *
 * ```text
 *
 *              ┌─────────────────── STREAM 1
 *              │ ┌─────────────s─── STREAM 2
 *       SAMPLE s │
 *              │ │
 *              ▼ ▼
 *         │           │
 *         │           │
 *         │           │
 *         │         ◄─┼─s─ PROBE
 * STATION └─────┬─────┘
 *               s
 *               │
 *               ▼
 *
 * ```
 *
 * # Metric
 *
 * Metrics are the smallest units of information processed by a Station.
 * They are defined by a unique identity, which is a metric name combined with
 * zero or more key/value labels, and a value.
 *
 * ```text
 *
 *          METRIC A
 *          ┌────────────────────────┐
 * IDENTITY │ disk.used{subject="A"} │
 * VALUE    │ 30.0                   │
 *          └────────────────────────┘
 *
 *           METRIC B
 *          ┌────────────────────────┐
 *          │ disk.used{subject="B"} │
 *          │ 97.0                   │
 *          └────────────────────────┘
 *
 * ```
 *
 * # Monitor
 *
 * Monitors are rules that allow the system to react to metrics.
 *
 * They contain a condition and an action. When a metric is received by a
 * station and matches the condition of a monitor, the action is executed.
 *
 * ```text
 *
 *                  METRIC
 *           ┌──────▼──────────┐
 * CONDITION │ disk.used >= 90 │
 * ACTION    │ send_alert      │
 *           └──────▼──────────┘
 *                  ACTION ──► send_alert()
 *
 * ```
 *
 * # Probe
 *
 * Probes are components that can generate metrics.
 * Depending on probe capabilities, it may be possible to retrieve information
 * about the local system, or poll a remote device across a network.
 *
 * For remote environments, a minimal station can be deployed directly to the
 * device to act as a transmitter by pushing samples upstream.
 *
 * ```text
 *
 * REMOTE DEVICE
 * ┌──────────────────────────────────────────┐
 * │ ┌──────┐   ┌─────────────┐   ┌─────────┐ │
 * │ │ DISK │──►│ SMART PROBE │──►│ STATION │ │
 * │ └──────┘   └─────────────┘   └────┬────┘ │
 * └───────────────────────────────────┼──────┘
 *                                     │
 *                                     │ NETWORK
 * LOCAL DEVICE                        │
 * ┌───────────────────────────────────│──────┐
 * │ ┌──────┐   ┌─────────────┐   ┌────▼────┐ │
 * │ │ DISK │──►│ SMART PROBE │──►│ STATION │ │
 * │ └──────┘   └─────────────┘   └────▲────┘ │
 * │            ┌─────────────┐────────┘      │        ┌───────────────┐
 * │            │ HTTP PROBE  │◄──────────────┼────────┤ REMOTE SERVER │
 * │            └─────────────┘               │        └───────────────┘
 * └──────────────────────────────────────────┘
 *
 * ```
 */

#![allow(dead_code, warnings)]

use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant};
use zenin::engine::Engine;
use zenin::thread::spawn_interval_loop;
use zenin::{now, probe};

fn leak<T>(value: T) -> &'static mut T {
    Box::leak(Box::new(value))
}

const DEFAULT_RING_SIZE: usize = 3600;

static SHUTDOWN: AtomicBool = AtomicBool::new(false);

fn main() {
    let mut engine = Engine::new(DEFAULT_RING_SIZE);
    let mut pcpu = probe::cpu::MedicCpuProbe::new(&mut engine);

    spawn_interval_loop(&SHUTDOWN, engine, pcpu);

    _ = wait_for_signals(&[SIGINT, SIGTERM]);
    SHUTDOWN.store(true, Ordering::Relaxed);
}

////////////////////////////////////////////////////////////////////////////////
// FFI
////////////////////////////////////////////////////////////////////////////////

use std::ffi::c_int;
use std::mem::MaybeUninit;

pub const SIGBLOCK: c_int = 0;
pub const SIGINT: c_int = 2;
pub const SIGTERM: c_int = 15;

#[repr(C)]
#[allow(non_camel_case_types)]
pub struct sigset_t {
    #[cfg(target_pointer_width = "32")]
    __val: [u32; 32],
    #[cfg(target_pointer_width = "64")]
    __val: [u64; 16],
}

unsafe extern "C" {
    fn sigemptyset(set: *mut sigset_t) -> c_int;
    fn sigaddset(set: *mut sigset_t, signum: c_int) -> c_int;
    fn pthread_sigmask(how: c_int, set: *const sigset_t, oldset: *mut sigset_t) -> c_int;
    fn sigwait(set: *const sigset_t, sig: *mut c_int) -> c_int;
}

pub fn wait_for_signals(signals: &[c_int]) -> c_int {
    unsafe {
        let mut set = MaybeUninit::<sigset_t>::uninit();
        sigemptyset(set.as_mut_ptr());
        for &sig in signals {
            sigaddset(set.as_mut_ptr(), sig);
        }

        pthread_sigmask(SIGBLOCK, set.as_ptr(), std::ptr::null_mut());

        let mut caught_sig: c_int = 0;
        sigwait(set.as_ptr(), &mut caught_sig);

        return caught_sig;
    }
}
