name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.4]
        node-version: [20.8.1]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
        working-directory: web
      - name: Build Web
        run: npm run build
        working-directory: web
      - name: Verify
        run: go mod verify
      - name: Build
        run: go build -v ./...
      - name: Vet
        run: go vet -v ./...
      - name: Test
        run: go test -race -v -vet=off ./...
